name: feather_ledger
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Persistence (DB)
  drift: ^2.23.1
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.5
  path: ^1.9.0

  # Persistence (Settings)
  shared_preferences: ^2.3.5

  # Navigation
  go_router: ^14.7.1

  # UI/Charts
  fl_chart: ^1.1.1
  flutter_heatmap_calendar: ^1.0.5
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  rrule: ^0.2.18
  uuid: ^4.5.2
  clock: ^1.1.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  drift_dev: ^2.23.1
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
